## Crops

In [ ]:
# import packages
import sys
import os
from dotenv import load_dotenv
from IPython.display import display, HTML

# Load environment variables from .env file
load_dotenv()

# import the API builder
from scoutmasterapi_builder.api import ScoutMasterAPI

The following Python snippet demonstrates how to initialize and authenticate with the ScoutMaster API using credentials stored in environment variables:

In [2]:
# Scoutmaster API - Credentials
client_id = os.getenv('SM_CLIENT_ID')
client_secret = os.getenv('SM_CLIENT_SECRET')
dev = os.getenv("DEV")

# Scoutmaster API - Init
SM_API = ScoutMasterAPI(dev, version="v3" )
SM_API.authenticate(client_id=client_id, client_secret=client_secret)

Initialized ScoutMaster API with host: https://dev-api.scoutmaster.nl/v3/
✅ Successfully authenticated ScoutMaster API
HOST: https://dev-api.scoutmaster.nl/v3/

In [ ]:
dev

Get crops as dataframe

In [3]:
df_crops = SM_API.crops()
df_crops

,code,created_at,updated_at,name
0,0,2025-06-06T15:26:05.656Z,2025-06-06T15:26:05.656Z,Onbekend
1,1010101,2024-11-06T20:50:47.673Z,2024-11-06T20:50:47.673Z,Potatos
2,1010201,2024-11-06T20:50:47.673Z,2024-11-06T20:50:47.673Z,Suikerbiet
3,1010202,2024-11-06T20:50:47.673Z,2024-11-06T20:50:47.673Z,Voederbiet
4,1020101,2024-11-06T20:50:47.673Z,2024-11-06T20:50:47.673Z,Wintertarwe
...,...,...,...,...
2653,9110102,2025-06-06T15:26:05.288Z,2025-06-06T15:26:05.288Z,Tijdelijk onbeteeld land
2654,9110103,2025-06-06T15:26:06.668Z,2025-06-06T15:26:06.668Z,Little Gem
2655,9110104,2025-06-06T15:26:07.013Z,2025-06-06T15:26:07.013Z,Roamaine sla
2656,9110105,2025-06-06T15:26:07.314Z,2025-06-06T15:26:07.314Z,Azolla
2657,9110106,2025-06-06T15:26:07.629Z,2025-06-06T15:26:07.629Z,Sedum

Order crops

In [4]:
df_crops = SM_API.crops(sort_by="name", order="desc", limit=10, page=1)
df_crops

      code                created_at                updated_at         name
0  1010202  2024-11-06T20:50:47.673Z  2024-11-06T20:50:47.673Z   Voederbiet
1  1020101  2024-11-06T20:50:47.673Z  2024-11-06T20:50:47.673Z  Wintertarwe
2  1020102  2024-11-06T20:50:47.673Z  2024-11-06T20:50:47.673Z  Wintergerst
3  1020103  2024-11-06T20:50:47.673Z  2024-11-06T20:50:47.673Z  Winterrogge
4  1020104  2024-11-06T20:50:47.673Z  2024-11-06T20:50:47.673Z    Triticale
5  1020105  2024-11-06T20:50:47.673Z  2024-11-06T20:50:47.673Z        Spelt
6  1020201  2024-11-06T20:50:47.673Z  2024-11-06T20:50:47.673Z   Zomertarwe
7  1020202  2024-11-06T20:50:47.673Z  2024-11-06T20:50:47.673Z   Zomergerst
8  1020203  2024-11-06T20:50:47.673Z  2024-11-06T20:50:47.673Z   Zomerrogge
9  1010201  2024-11-06T20:50:47.673Z  2024-11-06T20:50:47.673Z   Suikerbiet

In [5]:
crop_code = 1080101
df_crops = SM_API.crops()
crop = df_crops[df_crops['code'] == crop_code].iloc[0]
print(f"Crop Code: {crop['code']}")
print(f"Crop Name: {crop['name']}")

Crop Code: 1080101
Crop Name: Witlof

In [7]:
df_crops_varieties = SM_API.crop_varieties(crop_code=crop_code)
df_crops_varieties

,id,name,created_at,updated_at,crop_code,code
0,14765,Ras onbekend,2024-11-06T23:02:36.642Z,2024-11-06T23:02:36.642Z,1080101,10000
1,14766,Accent,2024-11-06T23:02:36.642Z,2024-11-06T23:02:36.642Z,1080101,10042
2,14767,Actius,2024-11-06T23:02:36.642Z,2024-11-06T23:02:36.642Z,1080101,10055
3,14768,Adou,2024-11-06T23:02:36.642Z,2024-11-06T23:02:36.642Z,1080101,10092
4,14769,Alliance,2024-11-06T23:02:36.642Z,2024-11-06T23:02:36.642Z,1080101,10222
...,...,...,...,...,...,...
126,23931,Jackpot OK-T14,2025-07-15T10:12:20.905Z,2025-07-15T10:12:20.905Z,1080101,20963
127,23932,Illumine,2025-07-15T10:12:20.933Z,2025-07-15T10:12:20.933Z,1080101,20964
128,23933,Agrine,2025-07-15T10:12:20.957Z,2025-07-15T10:12:20.957Z,1080101,20965
129,23934,Yarix,2025-07-15T10:12:20.980Z,2025-07-15T10:12:20.980Z,1080101,20966
130,23935,Olympic,2025-07-15T10:12:21.003Z,2025-07-15T10:12:21.003Z,1080101,16221